### PR TITLE
fix: Added queue for sending encrypted messages

### PR DESCRIPTION
**Pull request by ChaoticTempest**

### CODE REVIEW

**Review by itegulov — COMMENTED** [review]
Hmm, I might be misunderstanding the code, but wouldn't it just crash after the first failed send?

**Comment by ChaoticTempest** [comment]
@itegulov in the top level `state.advance` and `state.progress`, we have the error handling such that it would log the error. When the message fails to send in `MessageQueue`, it won't pop it, but keep it for next time, so once the protocol loop wraps around to the sending portion again, that's where it would retry

**Comment by ChaoticTempest** [comment]
previous comment wasn't entirely correct. If failed in the top level section, the state won't be saved, so the failures would indeed abort. Recent commit directly handles the failed sending of encrypted messages at the call site instead

**Review by itegulov — APPROVED** [review]
LGTM

**Pull request merged**
