### PR TITLE
Use Participants only in a context where they actually exist

### PR DESCRIPTION
**Pull request by volovyks**
ParticipantId should not be available in the `Initializing` context.

### CODE REVIEW

**Comment by ppca** [comment]
ParticipantId should not be available in the Initializing context. ---
what's the motivation for this?

**Comment by volovyks** [comment]
@ppca now on both contract and node sides we have 4 states:
- NotInitialized,
- Initializing(InitializingContractState)
- Running(RunningContractState)
- Resharing(ResharingContractState)

**Review by ppca — DISMISSED** [review]
LGTM. I think it'd be useful to add in PR title indicating contract change involved, so I'd know to redeploy contract as well.

**Comment by volovyks** [comment]
@ppca agree
Do you think we should automate contract deployment? At least for dev env.

**Review by ppca — APPROVED** [review]

**Pull request merged**
