### PR TITLE
Anshal/restrict ga workflow

### PR DESCRIPTION
**Pull request by anshal-savla**
Deploy to prod workflow will require approval from David, Kody or Xiangyi.

### CODE REVIEW

**Review by volovyks — COMMENTED** [review]
Should it be merged to the  main branch before it start functioning?
What if I remove this line in my PR?

**Comment by ppca** [comment]
is this based on the latest develop?

**Comment by ppca** [comment]
And also I saw there's another PR already merged? https://github.com/near/mpc/pull/829/files

**Comment by anshal-savla** [comment]
Yeah, this only works if the change in the main branch.

**Comment by volovyks** [comment]
@anshal-savla you are targeting develop in this PR again. And the history looks weird.
Closing in favor of https://github.com/near/mpc/pull/835
@anshal-savla @ppca please, take a look

**Pull request closed without merging**
